name: run-uv-unittests


on:
  push:
    branches: [ main ]
    paths-ignore: &common_exclusions
      - 'README.md'
      - '.devcontainer/**'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths-ignore: *common_exclusions

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/repos-uv.yaml

  build:
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' }}
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ matrix.package }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5 
      with:
        enable-cache: true
        cache-dependency-glob: "${{ matrix.package }}/uv.lock"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test dependencies
      run: uv sync --group test

    - name: Test with pytest - ${{ matrix.package }}
      run: uv run pytest -s --cov=. --cov-branch --cov-report=xml -v

    # - name: Upload coverage reports to Codecov
    #   # Codecov action runs from root, so we path into the folder for the report
    #   uses: codecov/codecov-action@v5
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     flags: ${{ matrix.package }}
    #     files: ./${{ matrix.package }}/coverage.xml